############################################################
#
# web访问端口号  约定：8088 （tomcat配置优先级高，避免被后续载入的本地配置覆盖)
#
############################################################
server:

  port: 8088



############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://172.17.0.15:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: Fq6m47LY%